theme: minima
title: SKT-TWR
author: shubham103
email: shbhmtwr19@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An ambivert middle class person having mindset to do something great for my country.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  shubham103 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
